# This code is generated by GPT-4o & modified by allenxu09.

from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import declarative_base, sessionmaker
from sqlalchemy.exc import SQLAlchemyError

Base = declarative_base()

# Database handler class
class Database:
    def __init__(self, database_url):
        """
        Initialize the database handler.

        Parameters:
            database_url (str): The database connection string (e.g., 'sqlite:///example.db').
        """
        self.engine = create_engine(database_url, echo=False)
        self.Session = sessionmaker(bind=self.engine)
        self.session = self.Session()


    def connect(self):
        """Create a new session."""
        if self.session is None:
            self.session = self.Session()

    def close(self):
        """Close the current session."""
        if self.session:
            self.session.close()
            self.session = None

    def insert_data(self, model, **kwargs):
        """
        Insert data into the database.

        Parameters:
            model: SQLAlchemy ORM model class.
            **kwargs: Data to insert, passed as keyword arguments.

        Returns:
            The inserted object or None if an error occurs.
        """
        self.connect()  # Ensure session is connected
        try:
            obj = model(**kwargs)
            self.session.add(obj)
            self.session.commit()
            return obj
        except SQLAlchemyError as e:
            self.session.rollback()
            print(f"Error inserting data: {e}")
            return None

    def query_data(self, model, **filters):
        """
        Query data from the database.

        Parameters:
            model: SQLAlchemy ORM model class.
            **filters: Filters to apply in the query (e.g., column=value).

        Returns:
            List of results or an empty list if no data is found or an error occurs.
        """
        self.connect()
        try:
            query = self.session.query(model)
            if filters:
                query = query.filter_by(**filters)
            return query.all()
        except SQLAlchemyError as e:
            print(f"Error querying data: {e}")
            return []

    def delete_data(self, model, **filters):
        """
        Delete data from the database.

        Parameters:
            model: SQLAlchemy ORM model class.
            **filters: Filters to apply in the query (e.g., column=value).

        Returns:
            Number of rows deleted.
        """
        self.connect()
        try:
            rows_deleted = self.session.query(model).filter_by(**filters).delete()
            self.session.commit()
            return rows_deleted
        except SQLAlchemyError as e:
            self.session.rollback()
            print(f"Error deleting data: {e}")
            return 0

    def update_data(self, model, filters, updates):
        """
        Update data in the database.

        Parameters:
            model: SQLAlchemy ORM model class.
            filters (dict): Filters to identify the records to update.
            updates (dict): Fields to update with their new values.

        Returns:
            Number of rows updated.
        """
        self.connect()
        try:
            rows_updated = self.session.query(model).filter_by(**filters).update(updates)
            self.session.commit()
            return rows_updated
        except SQLAlchemyError as e:
            self.session.rollback()
            print(f"Error updating data: {e}")
            return 0
